### ISSUE TITLE
how far..

### ISSUE THREAD

**Issue by danbates2** [cristi85/RFM69#1]
..did you get with this? It looks good, trying to test on a nucleo discovery f303, having some difficulty understanding how to catch the received radio packets.
any help appreciated.

**Comment by cristi85** [comment]
Hi Daniel

Please see this code sample:
[code_sample.txt](https://github.com/cristi85/RFM69/files/2780340/code_sample.txt)

Hope this helps

**Comment by danbates2** [comment]
It does, thanks.
Have you created an extra function RFM_DATA() to access the data[i] array created from RFM69_interruptHandler()?
I think I need to create that function..

**Comment by cristi85** [comment]
Please leave me your email address, it would be easier, I have also some updates to the library that are not (yet) on Github and I'll send you those also

**Comment by danbates2** [comment]
Great, thanks.
It's dgbates
[at]
